// @generated by protobuf-ts 2.9.6 with parameter server_grpc1
// @generated from protobuf file "protobuf-ts.proto" (package "ts", syntax proto3)
// tslint:disable
//
// This proto file is part of protobuf-ts. It defines custom options
// that are interpreted by @protobuf-ts/plugin.
//
// To use the options, add an import to this file:
//
//     import "protobuf-ts.proto";
//
// If you use @protobuf-ts/plugin, it should not be necessary to add a proto
// path to the file. @protobuf-ts/protoc automatically adds
// `--proto_path ./node_modules/@protobuf-ts/plugin` to your commands.
//
/**
 * The available client styles that can be generated by @protobuf-ts/plugin
 *
 * @generated from protobuf enum ts.ClientStyle
 */
export enum ClientStyle {
    /**
     * Do not emit a client for this service.
     *
     * @generated from protobuf enum value: NO_CLIENT = 0;
     */
    NO_CLIENT = 0,
    /**
     * Use the generic implementations of @protobuf-ts/runtime-rpc.
     * This is the default behaviour.
     *
     * @generated from protobuf enum value: GENERIC_CLIENT = 1;
     */
    GENERIC_CLIENT = 1,
    /**
     * Generate a client using @grpc/grpc-js (major version 1).
     *
     * @generated from protobuf enum value: GRPC1_CLIENT = 4;
     */
    GRPC1_CLIENT = 4
}
/**
 * The available server styles that can be generated by @protobuf-ts/plugin
 *
 * @generated from protobuf enum ts.ServerStyle
 */
export enum ServerStyle {
    /**
     * Do not emit a server for this service.
     * This is the default behaviour.
     *
     * @generated from protobuf enum value: NO_SERVER = 0;
     */
    NO_SERVER = 0,
    /**
     * Generate a generic server interface.
     * Adapters be used to serve the service, for example @protobuf-ts/grpc-backend
     * for gRPC.
     *
     * @generated from protobuf enum value: GENERIC_SERVER = 1;
     */
    GENERIC_SERVER = 1,
    /**
     * Generate a server for @grpc/grpc-js (major version 1).
     *
     * @generated from protobuf enum value: GRPC1_SERVER = 2;
     */
    GRPC1_SERVER = 2
}
