// @generated by protobuf-ts 2.9.6 with parameter server_grpc1
// @generated from protobuf file "user/v1/user.proto" (package "user", syntax proto3)
// tslint:disable
import { GetUserResponse } from "./user";
import { GetUserRequest } from "./user";
import { GetAllUsersResponse } from "./user";
import { GetAllUsersRequest } from "./user";
import type * as grpc from "@grpc/grpc-js";
/**
 * @generated from protobuf service user.UserService
 */
export interface IUserService extends grpc.UntypedServiceImplementation {
    /**
     * @generated from protobuf rpc: GetAllUsers(user.GetAllUsersRequest) returns (user.GetAllUsersResponse);
     */
    getAllUsers: grpc.handleUnaryCall<GetAllUsersRequest, GetAllUsersResponse>;
    /**
     * @generated from protobuf rpc: GetUser(user.GetUserRequest) returns (user.GetUserResponse);
     */
    getUser: grpc.handleUnaryCall<GetUserRequest, GetUserResponse>;
}
/**
 * @grpc/grpc-js definition for the protobuf service user.UserService.
 *
 * Usage: Implement the interface IUserService and add to a grpc server.
 *
 * ```typescript
 * const server = new grpc.Server();
 * const service: IUserService = ...
 * server.addService(userServiceDefinition, service);
 * ```
 */
export const userServiceDefinition: grpc.ServiceDefinition<IUserService> = {
    getAllUsers: {
        path: "/user.UserService/GetAllUsers",
        originalName: "GetAllUsers",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => GetAllUsersResponse.fromBinary(bytes),
        requestDeserialize: bytes => GetAllUsersRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(GetAllUsersResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(GetAllUsersRequest.toBinary(value))
    },
    getUser: {
        path: "/user.UserService/GetUser",
        originalName: "GetUser",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => GetUserResponse.fromBinary(bytes),
        requestDeserialize: bytes => GetUserRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(GetUserResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(GetUserRequest.toBinary(value))
    }
};
